services:
  - type: web
    name: project-pie-react
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
                        - key: PORT
                    value: 10000
      - key: API_HOST
        value: 0.0.0.0
      
      - key: DEBUG
        value: false
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://project-pie-react.onrender.com
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: POLYGON_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false 