# Default values for fa-backend

image:
  repository: ghcr.io/your-org/fa-backend
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8001

env:
  # Core Configuration
  - name: API_HOST
    value: "0.0.0.0"
  - name: API_PORT
    value: "8001"
  - name: DEBUG
    value: "false"
  
  # Database & Cache
  - name: DATABASE_URL
    value: "sqlite:///./financial_analytics.db"
  - name: REDIS_URL
    value: "redis://redis:6379"
  
  # API Keys (examples - replace with actual secrets)
  - name: ALPHA_VANTAGE_API_KEY
    valueFrom:
      secretKeyRef:
        name: api-keys
        key: alpha-vantage
  - name: OPENROUTER_API_KEY
    valueFrom:
      secretKeyRef:
        name: api-keys
        key: openrouter
  - name: COINGECKO_API_KEY
    valueFrom:
      secretKeyRef:
        name: api-keys
        key: coingecko
  
  # Security
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: secret-key

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false
  className: ""
  hosts:
    - host: fa-backend.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] 
 
 
 