apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fa-backend.fullname" . }}
  labels: {{- include "fa-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "fa-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "fa-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          env:
{{- with .Values.env }}
{{ toYaml . | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }} 
 
 
 