apiVersion: v1
kind: Service
metadata:
  name: {{ include "fa-backend.fullname" . }}
  labels: {{- include "fa-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "fa-backend.selectorLabels" . | nindent 4 }} 
 
 